language: python
python:
  - "3.8"  

cache: pip

install:
  - pip install -r requirements.txt  
  # - pip install python==3.8

before_script:
  - python manage.py migrate

after_script:
  - coveralls

script:
  - black --check .  
  - flake8 .
  - coverage run --source=mysite,polls manage.py test


deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>="
  secret_access_key:
    secure: "Encypted <secret-access-key>="
  region: "us-east-2"
  app: "example-app-name"
  env: "example-app-environment"
  bucket_name: "the-target-S3-bucket"